In [3]:
import numpy as np

In [4]:
np.arange(0,100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [5]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [6]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
np.zeros((6,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [8]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [9]:
np.ones((9,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [10]:
np.linspace(0,100,100) 

array([  0.        ,   1.01010101,   2.02020202,   3.03030303,
         4.04040404,   5.05050505,   6.06060606,   7.07070707,
         8.08080808,   9.09090909,  10.1010101 ,  11.11111111,
        12.12121212,  13.13131313,  14.14141414,  15.15151515,
        16.16161616,  17.17171717,  18.18181818,  19.19191919,
        20.2020202 ,  21.21212121,  22.22222222,  23.23232323,
        24.24242424,  25.25252525,  26.26262626,  27.27272727,
        28.28282828,  29.29292929,  30.3030303 ,  31.31313131,
        32.32323232,  33.33333333,  34.34343434,  35.35353535,
        36.36363636,  37.37373737,  38.38383838,  39.39393939,
        40.4040404 ,  41.41414141,  42.42424242,  43.43434343,
        44.44444444,  45.45454545,  46.46464646,  47.47474747,
        48.48484848,  49.49494949,  50.50505051,  51.51515152,
        52.52525253,  53.53535354,  54.54545455,  55.55555556,
        56.56565657,  57.57575758,  58.58585859,  59.5959596 ,
        60.60606061,  61.61616162,  62.62626263,  63.63

In [11]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [12]:
np.random.randn(7)

array([ 0.0833194 , -0.26877892,  2.58888911,  0.63237591,  0.76102324,
       -0.41097499, -2.04955335])

In [13]:
np.random.randn(2,2)

array([[ 0.18737567,  1.51133849],
       [-0.05925806,  0.44766273]])

In [14]:
np.random.randint(1,10) # rasgele arasından 

6

In [15]:
np.random.randint(1,10,5)

array([3, 5, 7, 6, 2])

In [16]:
np.random.randint(1,100,5)

array([19, 87, 87, 77, 17])

In [17]:
NumpyDizim= np.arange(30)

In [18]:
NumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [19]:
NumpyDizim.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [20]:
NumpyDizim.reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [21]:
NumpyDizim.max()

29

In [22]:
NumpyDizim.min()

0

In [23]:
NumpyDizim.argmax()

29

In [26]:
NumpyDizim.argmin()

0

In [27]:
dizim= np.arange(0,15)

In [28]:
dizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [29]:
dizim[5]

5

In [36]:
dizim[3:8]

array([3, 4, 5, 6, 7])

In [37]:
dizim[3:8] = -5

In [38]:
dizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [39]:
dizi1= np.arange(0,24)

In [40]:
dizi1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [52]:
x =dizi1[4:9]

In [53]:
x

array([4, 5, 6, 7, 8])

In [54]:
dizi1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [55]:
x[:]

array([4, 5, 6, 7, 8])

In [56]:
x[:]=700

In [57]:
x

array([700, 700, 700, 700, 700])

In [58]:
dizi1

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [98]:
ornekDizi=np.arange(0,24)

In [99]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [100]:
ornekDizi2 =ornekDizi.copy()

In [101]:
ornekDizi2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [102]:
ornekDizi3 = ornekDizi2[3:6]

In [104]:
ornekDizi3

array([3, 4, 5])

In [105]:
ornekDizi3[:]=800

In [106]:
ornekDizi3

array([800, 800, 800])

In [108]:
ornekDizi2

array([  0,   1,   2, 800, 800, 800,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [109]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

MATRİX

In [111]:
listem = [[10,20,30],[25,29,27],[32,30,78]]

In [112]:
listem

[[10, 20, 30], [25, 29, 27], [32, 30, 78]]

In [113]:
matrix= np.array(listem)

In [114]:
matrix

array([[10, 20, 30],
       [25, 29, 27],
       [32, 30, 78]])

In [115]:
matrix[0]

array([10, 20, 30])

In [116]:
matrix[0][2]

30

In [118]:
matrix[0,2]

30

In [119]:
matrix[1:,2]

array([27, 78])

In [120]:
matrix[2:,2]

array([78])

In [122]:
liste=[[1,20,8,9045,5],[54,96,8,7,6,2],[20,21,23,945,3],[5,6,7,98,458]]

In [125]:
matrix2 = np.array(liste)

In [126]:
matrix2

array([list([1, 20, 8, 9045, 5]), list([54, 96, 8, 7, 6, 2]),
       list([20, 21, 23, 945, 3]), list([5, 6, 7, 98, 458])], dtype=object)

In [129]:
matrix2[[0,2,3]]

array([list([1, 20, 8, 9045, 5]), list([20, 21, 23, 945, 3]),
       list([5, 6, 7, 98, 458])], dtype=object)

Operasyonlar

In [131]:
dizi4=np.random.randint(1,100,20)

In [132]:
dizi4

array([ 1, 27,  1, 27, 51, 43, 35, 70, 40, 71, 40, 18, 78, 38, 55, 46, 39,
       19, 11, 77])

In [136]:
 sonuc=dizi4>24

In [137]:
sonuc

array([False,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True, False,
       False,  True])

In [138]:
dizi4[sonuc]

array([27, 27, 51, 43, 35, 70, 40, 71, 40, 78, 38, 55, 46, 39, 77])

In [139]:
dizi4[dizi4>24]

array([27, 27, 51, 43, 35, 70, 40, 71, 40, 78, 38, 55, 46, 39, 77])

In [141]:
np.sqrt(dizi4) #karakök

array([1.        , 5.19615242, 1.        , 5.19615242, 7.14142843,
       6.55743852, 5.91607978, 8.36660027, 6.32455532, 8.42614977,
       6.32455532, 4.24264069, 8.83176087, 6.164414  , 7.41619849,
       6.78232998, 6.244998  , 4.35889894, 3.31662479, 8.77496439])